# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog:
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(266, 270)
        Dialog.setStyleSheet("color:rgb(85, 85, 127);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 60, 221, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 57 italic 14pt \"Ubuntu\";\n"
"    color: rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(255, 0, 0);\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(27, 100, 211, 111))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 16pt \"Chilanka\";\n"
"background-color: rgb(62, 72, 255);")
        self.label.setText("Wether today...")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 221, 28))
        self.lineEdit.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 57 italic 14pt \"Ubuntu\";\n"
"background-color: rgb(0, 0, 0);\n"
"border: none;")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Получить"))


if __name__ == '__main__':
    app = QtWidgets.QApplication([])
    application = Ui_Dialog()
    application.show()

    sys.exit(app.exec())
